spring:
  main:
    banner-mode: "off"

n26:
  transactionThreadCount: 20
  threadShutdownTimeoutInSeconds: 5
  maxTransactionAgeInSeconds: 60
  artificialDelay: false

logging:
  level:
    root: WARN
    com.n26: TRACE
